# Site settings
title: Tom Narock 
email: tnarockl@marymount.edu
description: > # this means to ignore newlines until "baseurl:"
  Homepage of Tom Narock, Assistant Professor of Information Technology, 
  Marymount University
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://narock.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username: narock 

# Build settings
markdown: redcarpet 
